### ISSUE TITLE
Update to 1.16 ? Is this mod alive?

### ISSUE THREAD

**Issue by T3sT3ro** [NarcolepticFrog/RedstoneMultimeter#6]
Is it?

**Comment by Xaver106** [comment]
If you are still interested and haven't found it already, there is an updated fabric version on [curseforge](https://www.curseforge.com/minecraft/mc-mods/redstone-multimeter-fabric), but for **Fabric**!

**Comment by T3sT3ro** [comment]
Yes, thank's found it earlier and forgot that this issue is still open.
